---
title: "Timeline"
author: 
date: "11/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(shinythemes)
library(tidyverse)
library(formatR)
library(DT)
library(ggrepel)
library(csv)
library(ggplot2)
library(utils)
```

```{r combine-data}
covid_19 <- read_csv("covid-19.csv")
mental_health <- read_csv("mental_health.csv")

covid_19 <- covid_19 %>%
  subset(select = -c(...1)) %>%
  rename(percentage_cases_state = percentage_cases_bar, percentage_deaths_state = percentage_deaths_bar)

mental_health <- mental_health %>%
  rename(state = State, week = WEEK)

covid_mental_health <- inner_join(mental_health, covid_19, by = c("state", "week"))

covid_mental_health_longer <- covid_mental_health %>%
  pivot_longer(cols = c("anxiety_percentage", "depression_percentage", "percentage_cases_state", "percentage_deaths_state"),
               names_to = "Response",
               values_to = "Percentage")

write_csv(covid_mental_health_longer, "covid_mental_health_longer.csv", append = FALSE)
write_csv(covid_mental_health, "covid_mental_health.csv", append = FALSE)
```


```{r ggplot}
# Basic line plot with points
graph <- ggplot(covid_mental_health, aes(x=week)) + 
  geom_point(aes(x=week, y=anxiety_percentage), color="red") +
  geom_point(aes(x=week, y=depression_percentage), color="blue") +
  geom_point(aes(y=percentage_cases_state),color="orange") +
  geom_point(aes(y=percentage_deaths_state),color="pink") +
  geom_line(aes(y=anxiety_percentage), color="red") +
  geom_line(aes(y=depression_percentage), color="blue") +
  geom_line(aes(y=percentage_cases_state), color="orange") +
  geom_line(aes(y=percentage_deaths_state, color="pink")) +
  scale_y_continuous(trans='log10')

graph

```

```{r}
twitter_sentiments <- read_csv2("twitter_sentiments.csv")
twitter_sentiments_national <- read_csv2("ntl_twitter_sentiments.csv")

covid_mental_health_longer_new <- covid_mental_health_longer %>%
  subset(select = c("state", "week", "Response", "Percentage")) %>%
  rename(response = Response, percentage = Percentage)

twitter_sentiments <- twitter_sentiments %>%
  subset(select = c("state", "week", "sentiments", "percentage_of_total_sentiment")) %>%
  rename(response = sentiments, percentage = percentage_of_total_sentiment) %>%
  filter(week != 0)

twitter_sentiments_national <- twitter_sentiments_national %>%
  mutate(percentage = (count/sum)*100) %>%
  subset(select = c("week", "sentiments", "percentage")) %>%
  add_column(state = "National") %>%
  filter(week != 0) %>%
  rename(response = sentiments)

twitter_sentiments_total <- rbind(twitter_sentiments, twitter_sentiments_national)

write_csv(twitter_sentiments_total, "twitter_sentiments_total.csv", append = FALSE)

timeline_data <- rbind(twitter_sentiments_total, covid_mental_health_longer_new)

write_csv(timeline_data, "timeline_data.csv", append = FALSE)
```

```{r}
timeline_table <- timeline_data %>%
  pivot_wider(
    names_from = response,
    values_from = percentage
  )

timeline_table <- timeline_table %>%
  rename(Anxiety = anxiety_percentage, Depression = depression_percentage, Negative = negative, Positive = positive, "Covid Cases" = percentage_cases_state, "Covid Deaths" = percentage_deaths_state) %>%
  subset(select = -c(anger, anticipation, disgust, fear, joy, sadness, surprise, trust))

timeline_graph <-timeline_table %>%
  pivot_longer(
    cols = c("Anxiety", "Depression", "Covid Cases", "Covid Deaths", "Negative", "Positive"),
    names_to = "response",
    values_to = "percentage"
  )

#write_csv(timeline_graph, "timeline_graph.csv", append = FALSE)

write_csv(timeline_table, "timeline_table.csv")
```

```{r}
timeline_table <- read_csv("timeline_table.csv")

timeline_table_new <- timeline_table %>%
  round(Negative, digits = 2)
```


