---
title: "mental-health"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
library(ggrepel)
library(csv)
```


```{r read-csv-weeks}
week_1 <- read_csv("data/mental-health/pulse2020_puf_01.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_2 <- read_csv("data/mental-health/pulse2020_puf_02.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_3 <- read_csv("data/mental-health/pulse2020_puf_03.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_4 <- read_csv("data/mental-health/pulse2020_puf_04.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_5 <- read_csv("data/mental-health/pulse2020_puf_05.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_6 <- read_csv("data/mental-health/pulse2020_puf_06.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_7 <- read_csv("data/mental-health/pulse2020_puf_07.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_8 <- read_csv("data/mental-health/pulse2020_puf_08.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_9 <- read_csv("data/mental-health/pulse2020_puf_09.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_10 <- read_csv("data/mental-health/pulse2020_puf_10.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_11 <- read_csv("data/mental-health/pulse2020_puf_11.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_12 <- read_csv("data/mental-health/pulse2020_puf_12.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_13 <- read_csv("data/mental-health/pulse2020_puf_13.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_14 <- read_csv("data/mental-health/pulse2020_puf_14.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_15 <- read_csv("data/mental-health/pulse2020_puf_15.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_16 <- read_csv("data/mental-health/pulse2020_puf_16.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_17 <- read_csv("data/mental-health/pulse2020_puf_17.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_18 <- read_csv("data/mental-health/pulse2020_puf_18.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_19 <- read_csv("data/mental-health/pulse2020_puf_19.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_20 <- read_csv("data/mental-health/pulse2020_puf_20.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_21 <- read_csv("data/mental-health/pulse2020_puf_21.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_22 <- read_csv("data/mental-health/pulse2021_puf_22.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_23 <- read_csv("data/mental-health/pulse2021_puf_23.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_24 <- read_csv("data/mental-health/pulse2021_puf_24.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_25 <- read_csv("data/mental-health/pulse2021_puf_25.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_26 <- read_csv("data/mental-health/pulse2021_puf_26.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_27 <- read_csv("data/mental-health/pulse2021_puf_27.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_28 <- read_csv("data/mental-health/pulse2021_puf_28.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_29 <- read_csv("data/mental-health/pulse2021_puf_29.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_30 <- haven::read_sas("data/mental-health/pulse2021_puf_30.sas7bdat") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_31 <- read_csv("data/mental-health/pulse2021_puf_31.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_32 <- read_csv("data/mental-health/pulse2021_puf_32.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_33 <- read_csv("data/mental-health/pulse2021_puf_33.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_34 <- read_csv("data/mental-health/pulse2021_puf_34.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_35 <- read_csv("data/mental-health/pulse2021_puf_35.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_36 <- read_csv("data/mental-health/pulse2021_puf_36.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_37 <- read_csv("data/mental-health/pulse2021_puf_37.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_38 <- read_csv("data/mental-health/pulse2021_puf_38.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
week_39 <- read_csv("data/mental-health/pulse2021_puf_39.csv") %>%
  subset(select = c(WEEK, ANXIOUS, WORRY, INTEREST, DOWN, EST_ST))
```


```{r mutate-percentages-phase_1}
phase1_mental_health <- rbind(week_1, week_2, week_3, week_4, week_5, week_6, week_7, week_8, week_9, week_10, week_11, week_12)

phase1_mental_health[phase1_mental_health == -99] <- 0
phase1_mental_health[phase1_mental_health == -88] <- 0

mental_health_1 <- phase1_mental_health %>%
  filter(EST_ST != 11) %>%
  mutate(ANXIETY_SCORE = ANXIOUS + WORRY) %>%
  mutate(DEPRESSION_SCORE = INTEREST + DOWN)

n <- nrow(mental_health_1)
  
mental_health_1 <- mental_health_1[1:n, ] %>%
  mutate(ANXIETY_ASSOCIATED = "")

  for(i in seq_len(n)) {
    if(mental_health_1$ANXIETY_SCORE[i] > 3) {
      mental_health_1$ANXIETY_ASSOCIATED[i] <- 1
    }
    else {
      mental_health_1$ANXIETY_ASSOCIATED[i] <- 0
    }
  }

mental_health_1 <- mental_health_1[1:n, ] %>%
  mutate(DEPRESSION_ASSOCIATED = "")

  for(i in seq_len(n)) {
    if(mental_health_1$DEPRESSION_SCORE[i] > 3) {
      mental_health_1$DEPRESSION_ASSOCIATED[i] <- 1
    }
    else {
      mental_health_1$DEPRESSION_ASSOCIATED[i] <- 0
    }
  }
 
write_csv(mental_health_1, "data/mental-health/mental_health_1.csv", append = FALSE)
```

```{r mutate-percentages-phase_2}
phase2_mental_health <- rbind(week_13, week_14, week_15, week_16, week_17)

phase2_mental_health[phase2_mental_health == -99] <- 0
phase2_mental_health[phase2_mental_health == -88] <- 0

mental_health_2 <- phase2_mental_health %>%
  filter(EST_ST != 11) %>%
  mutate(ANXIETY_SCORE = ANXIOUS + WORRY) %>%
  mutate(DEPRESSION_SCORE = INTEREST + DOWN)

n <- nrow(mental_health_2)
  
mental_health_2 <- mental_health_2[1:n, ] %>%
  mutate(ANXIETY_ASSOCIATED = "")

  for(i in seq_len(n)) {
    if(mental_health_2$ANXIETY_SCORE[i] > 3) {
      mental_health_2$ANXIETY_ASSOCIATED[i] <- 1
    }
    else {
      mental_health_2$ANXIETY_ASSOCIATED[i] <- 0
    }
  }

mental_health_2 <- mental_health_2[1:n, ] %>%
  mutate(DEPRESSION_ASSOCIATED = "")

  for(i in seq_len(n)) {
    if(mental_health_2$DEPRESSION_SCORE[i] > 3) {
      mental_health_2$DEPRESSION_ASSOCIATED[i] <- 1
    }
    else {
      mental_health_2$DEPRESSION_ASSOCIATED[i] <- 0
    }
  }

write_csv(mental_health_2, "data/mental-health/mental_health_2.csv", append = FALSE)
```


```{r mutate-percentages-phase_3}
phase3_mental_health <- rbind(week_18, week_19, week_20, week_21, week_22, week_23, week_24, week_25, week_26, week_27)

phase3_mental_health[phase3_mental_health == -99] <- 0
phase3_mental_health[phase3_mental_health == -88] <- 0

mental_health_3 <- phase3_mental_health %>%
  filter(EST_ST != 11) %>%
  mutate(ANXIETY_SCORE = ANXIOUS + WORRY) %>%
  mutate(DEPRESSION_SCORE = INTEREST + DOWN)

n <- nrow(mental_health_3)
  
mental_health_3 <- mental_health_3[1:n, ] %>%
  mutate(ANXIETY_ASSOCIATED = "")

  for(i in seq_len(n)) {
    if(mental_health_3$ANXIETY_SCORE[i] > 3) {
      mental_health_3$ANXIETY_ASSOCIATED[i] <- 1
    }
    else {
      mental_health_3$ANXIETY_ASSOCIATED[i] <- 0
    }
  }

mental_health_3 <- mental_health_3[1:n, ] %>%
  mutate(DEPRESSION_ASSOCIATED = "")

  for(i in seq_len(n)) {
    if(mental_health_3$DEPRESSION_SCORE[i] > 3) {
      mental_health_3$DEPRESSION_ASSOCIATED[i] <- 1
    }
    else {
      mental_health_3$DEPRESSION_ASSOCIATED[i] <- 0
    }
  }

write_csv(mental_health_3, "data/mental-health/mental_health_3.csv", append = FALSE)
```


```{r mutate-percentages-phase_3.1-3.2}
phase4_mental_health <- rbind(week_28, week_29, week_30, week_31, week_32, week_33, week_34, week_35, week_36, week_37, week_38, week_39)

phase4_mental_health[phase4_mental_health == -99] <- 0
phase4_mental_health[phase4_mental_health == -88] <- 0

mental_health_4 <- phase4_mental_health %>%
  filter(EST_ST != 11) %>%
  mutate(ANXIETY_SCORE = ANXIOUS + WORRY) %>%
  mutate(DEPRESSION_SCORE = INTEREST + DOWN)

mental_health_4 <- na.omit(mental_health_4)

n <- nrow(mental_health_4)
  
mental_health_4 <- mental_health_4[1:n, ] %>%
  mutate(ANXIETY_ASSOCIATED = "")

  for(i in seq_len(n)) {
    if(mental_health_4$ANXIETY_SCORE[i] > 3) {
      mental_health_4$ANXIETY_ASSOCIATED[i] <- 1
    }
    else {
      mental_health_4$ANXIETY_ASSOCIATED[i] <- 0
    }
  }

mental_health_4 <- mental_health_4[1:n, ] %>%
  mutate(DEPRESSION_ASSOCIATED = "")

  for(i in seq_len(n)) {
    if(mental_health_4$DEPRESSION_SCORE[i] > 3) {
      mental_health_4$DEPRESSION_ASSOCIATED[i] <- 1
    }
    else {
      mental_health_4$DEPRESSION_ASSOCIATED[i] <- 0
    }
  }

write_csv(mental_health_4, "data/mental-health/mental_health_4.csv", append = FALSE)

# combine datasets
total_mental_health <- rbind(mental_health_1, mental_health_2, mental_health_3, mental_health_4)

write_csv(total_mental_health, "data/mental-health/total_mental_health.csv", append = FALSE)
```

```{r combine-csv}
# import data
mental_health_1 <- read_csv("data/mental-health/mental_health_1.csv")
mental_health_2 <- read_csv("data/mental-health/mental_health_2.csv")
mental_health_3 <- read_csv("data/mental-health/mental_health_3.csv")
mental_health_4 <- read_csv("data/mental-health/mental_health_4.csv")
total_mental_health <- read_csv("data/mental-health/total_mental_health.csv")
averages <- read_csv("shiny/averages.csv")

# add column with state names
states <- averages %>%
  rename(Anxiety_score = "Anxiety Score", Depression_score = "Depression Score") %>%
  subset.data.frame(select = -c(Income, Anxious, Worry, Interest, Down, Anxiety_score, Depression_score)) %>%
  add_column(EST_ST = c(1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56))

# calculate anxiety and depression percentages
mental_health_new <- total_mental_health %>%
  mutate(EST_ST = as.numeric(EST_ST)) %>%
  group_by(EST_ST, WEEK) %>%
  summarize(count = n())

mental_health_new2 <- total_mental_health %>%
  mutate(EST_ST = as.numeric(EST_ST)) %>%
  group_by(EST_ST, WEEK) %>%
  arrange(EST_ST)

final_mental_health <- inner_join(mental_health_new, mental_health_new2, by = c("EST_ST", "WEEK"))

new_mental_health <- final_mental_health %>%
  mutate(anxiety_percentage = sum(ANXIETY_ASSOCIATED)/count, depression_percentage = sum(DEPRESSION_ASSOCIATED)/count) %>%
  subset(select = c(EST_ST, WEEK, count, anxiety_percentage, depression_percentage))

new_mental_health <- unique(new_mental_health)

new_mental_health <- inner_join(states, new_mental_health, by = "EST_ST")
```


```{r}
mental_health_national <- total_mental_health %>%
  mutate(EST_ST = as.numeric(EST_ST)) %>%
  group_by(WEEK) %>%
  summarize(count = n()) %>%
  mutate(count = as.numeric(count))

mental_health_national2 <- total_mental_health %>%
  mutate(EST_ST = as.numeric(EST_ST)) %>%
  group_by(WEEK) %>%
  arrange(WEEK)

final_mental_health_national <- inner_join(mental_health_national, mental_health_national2, by = c("WEEK")) 

final_mental_health_national <- final_mental_health_national %>%
  subset(select = -c(EST_ST)) %>%
  add_column(EST_ST = 0)

new_mental_health_national <- final_mental_health_national %>%
  mutate(anxiety_percentage = sum(ANXIETY_ASSOCIATED)/count, depression_percentage = sum(DEPRESSION_ASSOCIATED)/count) %>%
  subset(select = c(EST_ST, WEEK, count, anxiety_percentage, depression_percentage))

new_mental_health_national <- unique(new_mental_health_national)

new_mental_health_national <- new_mental_health_national %>%
  add_column(State = "National")

mental_health <- rbind(new_mental_health, new_mental_health_national)

write_csv(mental_health, "data/mental-health/mental_health.csv", append = FALSE)
```

