---
title: "roughDhyey.rmd"
author: "dm"
date: "10/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
```

```{r, eval = FALSE, show_col_types = FALSE}
library(dplyr)
library(readr)
library(grid)
uscovid <- read_csv("data/covid/uscovid.csv")
```

```{r}
us_week1 <- filter(uscovid, date >= as.Date("2020-04-23"), date <= as.Date("2020-05-05")) %>%
  mutate(week = 1)
us_week2 <- filter(uscovid, date >= as.Date("2020-05-07"), date <= as.Date("2020-05-12"))%>%
  mutate(week = 2)
us_week3 <- filter(uscovid, date >= as.Date("2020-05-14"), date <= as.Date("2020-05-19"))%>%
  mutate(week = 3)
us_week4 <- filter(uscovid, date >= as.Date("2020-05-21"), date <= as.Date("2020-05-26"))%>%
  mutate(week = 4)
us_week5 <- filter(uscovid, date >= as.Date("2020-05-28"), date <= as.Date("2020-06-02"))%>%
  mutate(week = 5)
us_week6 <- filter(uscovid, date >= as.Date("2020-06-04"), date <= as.Date("2020-06-09"))%>%
  mutate(week = 6)
us_week7 <- filter(uscovid, date >= as.Date("2020-06-11"), date <= as.Date("2020-06-16"))%>%
  mutate(week = 7)
us_week8 <- filter(uscovid, date >= as.Date("2020-06-18"), date <= as.Date("2020-06-23"))%>%
  mutate(week = 8)
us_week9 <- filter(uscovid, date >= as.Date("2020-06-25"), date <= as.Date("2020-06-30")) %>%
  mutate(week = 9)
us_week10 <- filter(uscovid, date >= as.Date("2020-07-02"), date <= as.Date("2020-07-07"))%>%
  mutate(week = 10)
us_week11 <- filter(uscovid, date >= as.Date("2020-07-09"), date <= as.Date("2020-07-14"))%>%
  mutate(week = 11)
us_week12 <- filter(uscovid, date >= as.Date("2020-07-16"), date <= as.Date("2020-07-21"))%>%
  mutate(week = 12)
us_week13 <- filter(uscovid, date >= as.Date("2020-08-19"), date <= as.Date("2020-08-31"))%>%
  mutate(week = 13)
us_week14 <- filter(uscovid, date >= as.Date("2020-09-02"), date <= as.Date("2020-09-14"))%>%
  mutate(week = 14)
us_week15 <- filter(uscovid, date >= as.Date("2020-09-16"), date <= as.Date("2020-09-28")) %>%
  mutate(week = 15)
us_week16 <- filter(uscovid, date >= as.Date("2020-09-30"), date <= as.Date("2020-10-12")) %>%
  mutate(week = 16)
us_week17 <- filter(uscovid, date >= as.Date("2020-10-14"), date <= as.Date("2020-10-26"))%>%
  mutate(week = 17)
us_week18 <- filter(uscovid, date >= as.Date("2020-10-28"), date <= as.Date("2020-11-09"))%>%
  mutate(week = 18)
us_week19 <- filter(uscovid, date >= as.Date("2020-11-11"), date <= as.Date("2020-11-23"))%>%
  mutate(week = 19)
us_week20 <- filter(uscovid, date >= as.Date("2020-11-25"), date <= as.Date("2020-12-07"))%>%
  mutate(week = 20)
us_week21 <- filter(uscovid, date >= as.Date("2020-12-09"), date <= as.Date("2020-12-21"))%>%
  mutate(week = 21)
us_week22 <- filter(uscovid, date >= as.Date("2021-01-06"), date <= as.Date("2021-01-18"))%>%
  mutate(week = 22)
us_week23 <- filter(uscovid, date >= as.Date("2021-01-20"), date <= as.Date("2021-02-01"))%>%
  mutate(week = 23)
us_week24 <- filter(uscovid, date >= as.Date("2021-02-03"), date <= as.Date("2021-02-15"))%>%
  mutate(week = 24)
us_week25 <- filter(uscovid, date >= as.Date("2021-02-17"), date <= as.Date("2021-03-01"))%>%
  mutate(week = 25)
us_week26 <- filter(uscovid, date >= as.Date("2021-03-03"), date <= as.Date("2021-03-15"))%>%
  mutate(week = 26)
us_week27 <- filter(uscovid, date >= as.Date("2021-03-17"), date <= as.Date("2021-03-29")) %>%
  mutate(week = 27) 
us_week28 <- filter(uscovid, date >= as.Date("2021-04-14"), date <= as.Date("2021-04-26")) %>%
  mutate(week = 28)
us_week29 <- filter(uscovid, date >= as.Date("2021-04-28"), date <= as.Date("2021-05-10")) %>%
  mutate(week = 29) 
us_week30 <- filter(uscovid, date >= as.Date("2021-05-12"), date <= as.Date("2021-05-24")) %>%
  mutate(week = 30)
us_week31 <- filter(uscovid, date >= as.Date("2021-05-26"), date <= as.Date("2021-06-07")) %>%
  mutate(week = 31)
us_week32 <- filter(uscovid, date >= as.Date("2021-06-09"), date <= as.Date("2021-06-21")) %>%
  mutate(week = 32)
us_week33 <- filter(uscovid, date >= as.Date("2021-06-23"), date <= as.Date("2021-07-05")) %>%
  mutate(week = 33) 
us_week34 <- filter(uscovid, date >= as.Date("2021-07-21"), date <= as.Date("2021-08-02")) %>%
  mutate(week = 34)
us_week35 <- filter(uscovid, date >= as.Date("2021-08-04"), date <= as.Date("2021-08-16")) %>%
  mutate(week = 35)
us_week36 <- filter(uscovid, date >= as.Date("2021-08-18"), date <= as.Date("2021-08-30")) %>%
  mutate(week = 36) 
us_week37 <- filter(uscovid, date >= as.Date("2021-09-01"), date <= as.Date("2021-09-13")) %>%
  mutate(week = 37)
us_week38 <- filter(uscovid, date >= as.Date("2021-09-15"), date <= as.Date("2021-09-27")) %>%
  mutate(week = 38)
us_week39 <- filter(uscovid, date >= as.Date("2021-09-29"), date <= as.Date("2021-10-11")) %>%
  mutate(week = 39)

us <- rbind(us_week1,us_week2,us_week3,us_week4,us_week5,us_week6,us_week7,us_week8,us_week9,us_week10,us_week11,us_week12,us_week13,us_week14,us_week15,us_week16,us_week17,us_week18,us_week19,us_week20,us_week21,us_week22,us_week23,us_week24,us_week25,us_week26,us_week27,us_week28,us_week29,us_week30,us_week31,us_week32,us_week33,us_week34,us_week35,us_week36,us_week37,us_week38,us_week39)

state_total_by_week <- us %>%
  group_by(state, week) %>%
  summarize(total_cases = sum(cases), total_deaths = sum(deaths))

us_total_by_week <- us %>%
  group_by(week) %>%
  summarize(total_cases_us = sum(cases), total_deaths_us = sum(deaths))

national_total_by_week <- us_total_by_week %>%
  mutate(state = "National") %>%
  rename("total_cases" = total_cases_us,"total_deaths" = total_deaths_us)

final_state_total_by_week <- rbind(state_total_by_week,national_total_by_week)

us_total_by_state <- us %>%
  group_by(state) %>%
  summarize(total_cases_state_all_weeks = sum(cases), total_deaths_state_all_weeks = sum(deaths)) %>%
  add_row(state="National",
          total_cases_state_all_weeks=sum(us_total_by_state$total_cases_state_all_weeks),
          total_deaths_state_all_weeks=sum(us_total_by_state$total_deaths_state_all_weeks))

us_joined_spatial <- inner_join(final_state_total_by_week,us_total_by_week,by = "week")

us_joined_bar <- inner_join(us_joined_spatial,us_total_by_state,by = "state")

covid_us_final <- us_joined_bar %>% 
  mutate(percentage_cases_spatial = (total_cases/total_cases_us) *100,
         percentage_deaths_spatial = (total_deaths/total_deaths_us) *100,
         percentage_cases_bar = (total_cases/total_cases_state_all_weeks) *100,
         percentage_deaths_bar = (total_deaths/total_deaths_state_all_weeks) *100
         )

write.csv(covid_us_final, "covid_updated.csv")
write.csv(us, "us.csv")
```

```{r}
timeline_graph_up <- read_csv("timeline_graph2.csv") %>%
  filter(response == "Covid Cases",state == "National") %>%
  mutate(diff = c(0.0502819,-0.02102229,0.003524543,0.00346709,0.003278399,0.00338682,0.003405226,0.004120342,0.005832997,0.007556452,0.00889334,0.01023633,0.1948606,0.02660811,0.0270676,0.03067617,0.03842486,0.05539291,0.09359305,0.1149099,0.1406222,0.2908593,0.12467,0.08348704,0.05102942,0.04244973,0.03846894,0.08787491,0.0341228,0.02320477,0.01348673,0.008044775,0.008935341,0.05086234,0.07038062,0.09734421,0.1046851,0.09571224,0.07334682))
#for (w in timeline_graph$week) {
#  print(timeline_graph$percentage[w+1] - timeline_graph$percentage[w])
#}

ggplot(data = timeline_graph_up,
           mapping = aes(x = week,
                         y = diff)) +
      geom_line(aes(x = week,
                    y = diff)) +
      geom_point(aes(x = week,
                     y = diff)) +
      #geom_hline(yintercept = 19.933939, linetype = "dashed") +
  geom_smooth(method = "lm", se = TRUE, color = "blue") +
  
      theme(plot.title = element_text(size=15), 
            plot.subtitle = element_text(size=10),
            axis.text = element_text(size=10),
            axis.title = element_text(size=10),
            legend.text = element_text(size=10),
            legend.title = element_text(size=10),
            legend.key.size = unit(1, 'cm')) +
            #scale_y_continuous(trans='log10') +

      #scale_colour_manual(values = c("Covid Cases" = "slateblue1")) +
      labs(title = "The Change in Covid Cases/Deaths",
           subtitle = "During the Covid-19 Period",
           y = "Percentage of change in Covid-19 cases",
           x = "Week")
cor(y = timeline_graph_up$diff,x = timeline_graph_up$week)
```

