---
title: "Untitled"
author: "dm"
date: "11/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)

```

```{r, fig.cap = "Fig. # - Control"}
# Cases
library(usmap)
covid_19_spatial <- read_csv("covid_19_spatial.csv")
covdata <- covid_19_spatial %>%
            filter(week %in% c(3:12,14:17,35:39))%>%
            select(c("state", 
                     "percentage_cases_bar",
                     "percentage_deaths_bar")) %>%
            group_by(state) %>%
            summarize(percentage_cases_bar =
                        mean(percentage_cases_bar),
                      percentage_deaths_bar =
                        mean(percentage_deaths_bar)) 

plot_usmap(data = covdata, values = "percentage_cases_bar") +
            viridis::scale_fill_viridis(name = "Percentages of Cases", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Cases",
                 subtitle = "During COVID-19 (Weeks 3-12, 14-17, 35-39)",
                 caption = paste("Percentage = average of number of new cases for the state during this time period over number of new cases during weeks 1-39", " ", sep="\n"))


# anxiety

mendata <- mental_health_spatial %>%
            filter(week %in% c(3:12,14:17,35:39))%>%
            select(c("state", "anxiety_percentage", "depression_percentage")) %>%
            group_by(state) %>%
            summarize(
              anxiety_percentage = mean(anxiety_percentage),
              depression_percentage = mean(depression_percentage))

plot_usmap(data = mendata, values = "anxiety_percentage") +
            viridis::scale_fill_viridis(name = "Percentages of Anxiety", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=12), 
                  plot.subtitle = element_text(size=9),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=10),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(hjust = 0)) +
            labs(title = "The Distribution of Percentages of People Associated with Anxiety",
                 subtitle = "During COVID-19 (Weeks 3-12, 14-17, 35-39)", 
                 caption = paste("Percentage = average of number of people with anxiety over number of people who took the survey during this time period", " ", sep="\n"))


```

```{r}
library(usmap)
covid_19_spatial <- read_csv("covid_19_spatial.csv")

################# Week 12-14 ######################
covdata <- covid_19_spatial %>%
            filter(week %in% c(12:14))%>%
            select(c("state", 
                     "percentage_cases_bar",
                     "percentage_deaths_bar")) %>%
            group_by(state) %>%
            summarize(percentage_cases_bar =
                        mean(percentage_cases_bar),
                      percentage_deaths_bar =
                        mean(percentage_deaths_bar)) 

plot_usmap(data = covdata, values = "percentage_cases_bar") +
            viridis::scale_fill_viridis(name = "Percentages of Cases", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Cases",
                 subtitle = "During COVID-19 (Weeks 12-14)",
                 caption = paste("Percentage = average of number of new cases for the state during this time period over number of new cases during weeks 12-14", " ", sep="\n"))

################# Week 18-25 ######################
covdata <- covid_19_spatial %>%
            filter(week %in% c(18:25))%>%
            select(c("state", 
                     "percentage_cases_bar",
                     "percentage_deaths_bar")) %>%
            group_by(state) %>%
            summarize(percentage_cases_bar =
                        mean(percentage_cases_bar),
                      percentage_deaths_bar =
                        mean(percentage_deaths_bar)) 

plot_usmap(data = covdata, values = "percentage_cases_bar") +
            viridis::scale_fill_viridis(name = "Percentages of Cases", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Cases",
                 subtitle = "During COVID-19 (Weeks 18-25)",
                 caption = paste("Percentage = average of number of new cases for the state during this time period over number of new cases during weeks 18-25", " ", sep="\n"))

################# Week 29-34 ######################
covdata <- covid_19_spatial %>%
            filter(week %in% c(29:34))%>%
            select(c("state", 
                     "percentage_cases_bar",
                     "percentage_deaths_bar")) %>%
            group_by(state) %>%
            summarize(percentage_cases_bar =
                        mean(percentage_cases_bar),
                      percentage_deaths_bar =
                        mean(percentage_deaths_bar)) 

plot_usmap(data = covdata, values = "percentage_cases_bar") +
            viridis::scale_fill_viridis(name = "Percentages of Cases", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Cases",
                 subtitle = "During COVID-19 (Weeks 29-34)",
                 caption = paste("Percentage = average of number of new cases for the state during this time period over number of new cases during weeks 29-34", " ", sep="\n"))
```

```{r, fig.cap = "Fig. # - Mental health"}
library(usmap)
library(dplyr)
library(tidyverse)
mental_health_spatial <- read_csv("mental_health_spatial.csv")

############# Week 29:34 Anxiety ###############
mendata <- mental_health_spatial %>%
            filter(week %in% 29:34)%>%
            select(c("state", "anxiety_percentage", "depression_percentage")) %>%
            group_by(state) %>%
            summarize(
              anxiety_percentage = mean(anxiety_percentage),
              depression_percentage = mean(depression_percentage))

plot_usmap(data = mendata, values = "anxiety_percentage") +
            viridis::scale_fill_viridis(name = "Percentages of Anxiety", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=12), 
                  plot.subtitle = element_text(size=9),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=10),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(hjust = 0)) +
            labs(title = "The Distribution of Percentages of People Associated with Anxiety",
                 subtitle = "During COVID-19 (Weeks 29-34)", 
                 caption = paste("Percentage = average of number of people with anxiety over number of people who took the survey during this time period", " ", sep="\n"))

############# Week 18:25 Anxiety ###############
mendata <- mental_health_spatial %>%
            filter(week %in% 18:25)%>%
            select(c("state", "anxiety_percentage", "depression_percentage")) %>%
            group_by(state) %>%
            summarize(
              anxiety_percentage = mean(anxiety_percentage),
              depression_percentage = mean(depression_percentage))

plot_usmap(data = mendata, values = "anxiety_percentage") +
            viridis::scale_fill_viridis(name = "Percentages of Anxiety", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=12), 
                  plot.subtitle = element_text(size=9),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=10),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(hjust = 0)) +
            labs(title = "The Distribution of Percentages of People Associated with Anxiety",
                 subtitle = "During COVID-19 (Weeks 18-25)", 
                 caption = paste("Percentage = average of number of people with anxiety over number of people who took the survey during this time period", " ", sep="\n"))

############# Week 12:14 Anxiety ###############
mendata <- mental_health_spatial %>%
            filter(week %in% 12:14)%>%
            select(c("state", "anxiety_percentage", "depression_percentage")) %>%
            group_by(state) %>%
            summarize(
              anxiety_percentage = mean(anxiety_percentage),
              depression_percentage = mean(depression_percentage))

plot_usmap(data = mendata, values = "anxiety_percentage") +
            viridis::scale_fill_viridis(name = "Percentages of Anxiety", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=12), 
                  plot.subtitle = element_text(size=9),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=10),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(hjust = 0)) +
            labs(title = "The Distribution of Percentages of People Associated with Anxiety",
                 subtitle = "During COVID-19 (Weeks 12-14)", 
                 caption = paste("Percentage = average of number of people with anxiety over number of people who took the survey during this time period", " ", sep="\n"))

############# Week 2 Anxiety ###############
mendata <- mental_health_spatial %>%
            filter(week == 2)%>%
            select(c("state", "anxiety_percentage", "depression_percentage")) %>%
            group_by(state) %>%
            summarize(
              anxiety_percentage = mean(anxiety_percentage),
              depression_percentage = mean(depression_percentage))

plot_usmap(data = mendata, values = "anxiety_percentage") +
            viridis::scale_fill_viridis(name = "Percentages of Anxiety", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=12), 
                  plot.subtitle = element_text(size=9),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=10),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(hjust = 0)) +
            labs(title = "The Distribution of Percentages of People Associated with Anxiety",
                 subtitle = "During COVID-19 (Week 2)", 
                 caption = paste("Percentage = number of people with anxiety over number of people who took the survey during this week", " ", sep="\n"))

############# Week 3 Anxiety ###############
mendata <- mental_health_spatial %>%
            filter(week == 3)%>%
            select(c("state", "anxiety_percentage", "depression_percentage")) %>%
            group_by(state) %>%
            summarize(
              anxiety_percentage = mean(anxiety_percentage),
              depression_percentage = mean(depression_percentage))

plot_usmap(data = mendata, values = "anxiety_percentage") +
            viridis::scale_fill_viridis(name = "Percentages of Anxiety", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=12), 
                  plot.subtitle = element_text(size=9),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=10),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(hjust = 0)) +
            labs(title = "The Distribution of Percentages of People Associated with Anxiety",
                 subtitle = "During COVID-19 (Week 3)", 
                 caption = paste("Percentage = number of people with anxiety over number of people who took the survey during this week", " ", sep="\n"))

############# Week 18 Anxiety ###############
mendata <- mental_health_spatial %>%
            filter(week == 18)%>%
            select(c("state", "anxiety_percentage", "depression_percentage")) %>%
            group_by(state) %>%
            summarize(
              anxiety_percentage = mean(anxiety_percentage),
              depression_percentage = mean(depression_percentage))

plot_usmap(data = mendata, values = "anxiety_percentage") +
            viridis::scale_fill_viridis(name = "Percentages of Anxiety", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=12), 
                  plot.subtitle = element_text(size=9),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=10),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(hjust = 0)) +
            labs(title = "The Distribution of Percentages of People Associated with Anxiety",
                 subtitle = "During COVID-19 (Week 18)", 
                 caption = paste("Percentage = number of people with anxiety over number of people who took the survey during this week", " ", sep="\n"))
```

# For population-biased cases graph:
title: The Distribution of Percentages of New COVID-19 Cases
subtitle: During Weeks #-#

Percentage = average of number of new cases for the state over number of new cases in the nation during this time period

```{r new york case study}
library(usmap)
covid_19_spatial <- read_csv("covid_19_spatial.csv")

############## Week 12-14 Population Biased Cases ############
covdataBiased <- covid_19_spatial %>%
            filter(week %in% c(12:14))%>%
            select(c("state", "percentage_cases_spatial", "percentage_deaths_spatial")) %>%
            group_by(state) %>%
            summarize(
              percentage_cases_spatial =mean(percentage_cases_spatial),
              percentage_deaths_spatial=mean(percentage_deaths_spatial)
              )
plot_usmap(data = covdataBiased, values = "percentage_cases_spatial") +
            viridis::scale_fill_viridis(name = "Percentages of Cases", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Cases",subtitle = "During Weeks 12-14",
                 caption = paste("Percentage is average of number of new cases for the state over number of new cases in the nation during this time period", " ", sep="\n"))

############# Week 12-14 Population unbiased Cases ############
covdata <- covid_19_spatial %>%
            filter(week %in% c(12:14))%>%
            select(c("state", 
                     "percentage_cases_bar",
                     "percentage_deaths_bar")) %>%
            group_by(state) %>%
            summarize(percentage_cases_bar =
                        mean(percentage_cases_bar),
                      percentage_deaths_bar =
                        mean(percentage_deaths_bar)) 

plot_usmap(data = covdata, values = "percentage_cases_bar") +
            viridis::scale_fill_viridis(name = "Percentages of Cases", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Cases",
                 subtitle = "During COVID-19 (Weeks 12-14)",
                 caption = paste("Percentage is average of number of new cases for the state during this time period over number of new cases during weeks 12-14", " ", sep="\n"))

############## Week 12-14 Population Biased Deaths ############
covdataBiased <- covid_19_spatial %>%
            filter(week %in% c(12:14))%>%
            select(c("state", "percentage_cases_spatial", "percentage_deaths_spatial")) %>%
            group_by(state) %>%
            summarize(
              percentage_cases_spatial =mean(percentage_cases_spatial),
              percentage_deaths_spatial=mean(percentage_deaths_spatial)
              )
plot_usmap(data = covdataBiased, values = "percentage_deaths_spatial") +
            viridis::scale_fill_viridis(name = "Percentages of Deaths", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Deaths",subtitle = "During Weeks 12-14",
                 caption = paste("Percentage is average of number of new deaths for the state over number of new deaths in the nation during this time period", " ", sep="\n"))

############# Week 12-14 Population unbiased Deaths ############
covdata <- covid_19_spatial %>%
            filter(week %in% c(12:14))%>%
            select(c("state", 
                     "percentage_cases_bar",
                     "percentage_deaths_bar")) %>%
            group_by(state) %>%
            summarize(percentage_cases_bar =
                        mean(percentage_cases_bar),
                      percentage_deaths_bar =
                        mean(percentage_deaths_bar)) 

plot_usmap(data = covdata, values = "percentage_deaths_bar") +
            viridis::scale_fill_viridis(name = "Percentages of Deaths", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Deaths",
                 subtitle = "During COVID-19 (Weeks 12-14)",
                 caption = paste("Percentage is average of number of new deaths for the state during this time period over number of new deaths during weeks 12-14", " ", sep="\n"))

##############################################################################################################################################

############## Week 18-25 Population Biased Cases ############
covdataBiased <- covid_19_spatial %>%
            filter(week %in% c(18:25))%>%
            select(c("state", "percentage_cases_spatial", "percentage_deaths_spatial")) %>%
            group_by(state) %>%
            summarize(
              percentage_cases_spatial =mean(percentage_cases_spatial),
              percentage_deaths_spatial=mean(percentage_deaths_spatial)
              )
plot_usmap(data = covdataBiased, values = "percentage_cases_spatial") +
            viridis::scale_fill_viridis(name = "Percentages of Cases", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Cases",subtitle = "During Weeks 18-25",
                 caption = paste("Percentage is average of number of new cases for the state over number of new cases in the nation during this time period", " ", sep="\n"))

############# Week 18-25 Population unbiased Cases ############
covdata <- covid_19_spatial %>%
            filter(week %in% c(18:25))%>%
            select(c("state", 
                     "percentage_cases_bar",
                     "percentage_deaths_bar")) %>%
            group_by(state) %>%
            summarize(percentage_cases_bar =
                        mean(percentage_cases_bar),
                      percentage_deaths_bar =
                        mean(percentage_deaths_bar)) 

plot_usmap(data = covdata, values = "percentage_cases_bar") +
            viridis::scale_fill_viridis(name = "Percentages of Cases", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Cases",
                 subtitle = "During COVID-19 (Weeks 18-25)",
                 caption = paste("Percentage is average of number of new cases for the state during this time period over number of new cases during weeks 18-25", " ", sep="\n"))

############## Week 18-25 Population Biased Deaths ############
covdataBiased <- covid_19_spatial %>%
            filter(week %in% c(18:25))%>%
            select(c("state", "percentage_cases_spatial", "percentage_deaths_spatial")) %>%
            group_by(state) %>%
            summarize(
              percentage_cases_spatial =mean(percentage_cases_spatial),
              percentage_deaths_spatial=mean(percentage_deaths_spatial)
              )
plot_usmap(data = covdataBiased, values = "percentage_deaths_spatial") +
            viridis::scale_fill_viridis(name = "Percentages of Deaths", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Deaths",subtitle = "During Weeks 18-25",
                 caption = paste("Percentage is average of number of new deaths for the state over number of new deaths in the nation during this time period", " ", sep="\n"))

############# Week 18-25 Population unbiased Deaths ############
covdata <- covid_19_spatial %>%
            filter(week %in% c(18:25))%>%
            select(c("state", 
                     "percentage_cases_bar",
                     "percentage_deaths_bar")) %>%
            group_by(state) %>%
            summarize(percentage_cases_bar =
                        mean(percentage_cases_bar),
                      percentage_deaths_bar =
                        mean(percentage_deaths_bar)) 

plot_usmap(data = covdata, values = "percentage_deaths_bar") +
            viridis::scale_fill_viridis(name = "Percentages of Deaths", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Deaths",
                 subtitle = "During COVID-19 (Weeks 18-25)",
                 caption = paste("Percentage is average of number of new deaths for the state during this time period over number of new deaths during weeks 18-25", " ", sep="\n"))

##############################################################################################################################################

############## Week 29-34 Population Biased Cases ############
covdataBiased <- covid_19_spatial %>%
            filter(week %in% c(29:34))%>%
            select(c("state", "percentage_cases_spatial", "percentage_deaths_spatial")) %>%
            group_by(state) %>%
            summarize(
              percentage_cases_spatial =mean(percentage_cases_spatial),
              percentage_deaths_spatial=mean(percentage_deaths_spatial)
              )
plot_usmap(data = covdataBiased, values = "percentage_cases_spatial") +
            viridis::scale_fill_viridis(name = "Percentages of Cases", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Cases",subtitle = "During Weeks 29-34",
                 caption = paste("Percentage is average of number of new cases for the state over number of new cases in the nation during this time period", " ", sep="\n"))

############# Week 29-34 Population unbiased Cases ############
covdata <- covid_19_spatial %>%
            filter(week %in% c(29:34))%>%
            select(c("state", 
                     "percentage_cases_bar",
                     "percentage_deaths_bar")) %>%
            group_by(state) %>%
            summarize(percentage_cases_bar =
                        mean(percentage_cases_bar),
                      percentage_deaths_bar =
                        mean(percentage_deaths_bar)) 

plot_usmap(data = covdata, values = "percentage_cases_bar") +
            viridis::scale_fill_viridis(name = "Percentages of Cases", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Cases",
                 subtitle = "During COVID-19 (Weeks 29-34)",
                 caption = paste("Percentage is average of number of new cases for the state during this time period over number of new cases during weeks 29-34", " ", sep="\n"))

############## Week 29-34 Population Biased Deaths ############
covdataBiased <- covid_19_spatial %>%
            filter(week %in% c(29:34))%>%
            select(c("state", "percentage_cases_spatial", "percentage_deaths_spatial")) %>%
            group_by(state) %>%
            summarize(
              percentage_cases_spatial =mean(percentage_cases_spatial),
              percentage_deaths_spatial=mean(percentage_deaths_spatial)
              )
plot_usmap(data = covdataBiased, values = "percentage_deaths_spatial") +
            viridis::scale_fill_viridis(name = "Percentages of Deaths", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Deaths",subtitle = "During Weeks 29-34",
                 caption = paste("Percentage is average of number of new deaths for the state over number of new deaths in the nation during this time period", " ", sep="\n"))

############# Week 29-34 Population unbiased Deaths ############
covdata <- covid_19_spatial %>%
            filter(week %in% c(29:34))%>%
            select(c("state", 
                     "percentage_cases_bar",
                     "percentage_deaths_bar")) %>%
            group_by(state) %>%
            summarize(percentage_cases_bar =
                        mean(percentage_cases_bar),
                      percentage_deaths_bar =
                        mean(percentage_deaths_bar)) 

plot_usmap(data = covdata, values = "percentage_deaths_bar") +
            viridis::scale_fill_viridis(name = "Percentages of Deaths", option = "magma", direction = -1) +
            theme_void() +
            theme(plot.title = element_text(size=15), 
                  plot.subtitle = element_text(size=11),
                  legend.text = element_text(size=10),
                  legend.title = element_text(size=11),
                  legend.key.size = unit(1, 'cm'),
                  plot.caption.position = "plot",
                  plot.caption = element_text(size = 8.5, hjust = 0)) +
            labs(title = "The Distribution of Percentages of New COVID-19 Deaths",
                 subtitle = "During COVID-19 (Weeks 29-34)",
                 caption = paste("Percentage is average of number of new deaths for the state during this time period over number of new deaths during weeks 29-34", " ", sep="\n"))


```