---
title: "Untitled"
author: "dm"
date: "11/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(shinythemes)
library(tidyverse)
library(formatR)
library(DT)
library(ggrepel)
library(csv)
library(ggplot2)
```

```{r combine-data}
covid_19 <- read_csv("data/covid/covid_19.csv")
mental_health <- read_csv("data/mental-health/mental_health.csv")

mental_health <- mental_health %>%
  rename(state = State, week = WEEK)

covid_mental_health <- inner_join(mental_health, covid_19, by = c("state", "week"))

covid_mental_health_selected_state <- covid_mental_health %>%
  filter(state == "Alabama") %>%
  mutate(state_case_perc = total_cases/sum(total_cases)*100,
         state_death_perc = total_deaths/sum(total_cases)*100)

covid_mental_health_selected_state
library(ggplot2)
# Basic line plot with points
graph <- ggplot(covid_mental_health_selected_state, aes(x=week)) + geom_point(aes(x=week, y=anxiety_percentage), color="red") +
 geom_point(aes(x=week, y=depression_percentage), color="blue") +
  geom_point(aes(y=state_death_perc ),color="orange") +
  geom_point(aes(y=state_case_perc),color="pink") +
  geom_line(aes(y=anxiety_percentage), color="red") +
  geom_line(aes(y=depression_percentage), color="blue") +
  geom_line(aes(y=state_case_perc, color="pink")) +
  geom_line(aes(y=state_death_perc), color="orange") +
  scale_y_continuous(trans='log10')

graph

```

